# -*- coding:utf-8 -*-

import os
import math

DOUBLE_PI = 2 * math.pi

SCREEN_W, SCREEN_H = 800, 600
CENTER_X, CENTER_Y = SCREEN_W * 0.5, SCREEN_H * 0.5
WIDTH, HEIGHT = SCREEN_W, SCREEN_H
GRID_SIZE = 10

ENGINE = None
SCREEN = None

L_MOUSE_BUTTON = 1
M_MOUSE_BUTTON = 2
R_MOUSE_BUTTON = 3

FPS_AVG_FRAME_NUM = 10  # FPS 多少帧刷新一次。 取均值。

MAX_SPEED = 300.0
ACTOR_NUM = 100
VISION_SIZE = 10.0

ROOT_PATH = os.getcwd() + '/../'
RES_PATH = ROOT_PATH + 'res'
TMP_PATH = RES_PATH + 'tmp'

